config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  #devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  #devise_scope :user do
  #  get 'forget', to: 'users/passwords#forget'
  #  patch 'update_password', to: 'users/passwords#update_password'
  #end

  #require 'sidekiq/web'
  #require 'sidekiq/cron/web'
  #mount Sidekiq::Web => '/sidekiq'


  resources :labs, :only => [:index, :show]
  resources :members, :only => [:index, :show]
  resources :results, :only => [:index, :show]
  resources :reports, :only => [:index, :show] do
    get :cstr, :on => :collection
    get :serv, :on => :collection
    get :know, :on => :collection
  end
  resources :activities, :only => [:index, :show]
  resources :manages, :only => [:index, :show]
  resources :notices, :only => [:index, :show]
  resources :infos, :only => [:index, :show]

  #resources :controls, :only => [:index]

  #resources :systems, :only => [] do
  #  get :send_confirm_code, :on => :collection
  #end

  #resources :users, :only => []  do
  #  get :center, :on => :collection
  #  get :alipay_return, :on => :collection
  #  post :alipay_notify, :on => :collection
  #  get :mobile_authc_new, :on => :member
  #  post :mobile_authc_create, :on => :member
  #  get :mobile_authc_status, :on => :member

  #end

  #resources :orders, :only => [:new, :create] do
  #  get :pay, :on => :collection
  #  get :alipay_return, :on => :collection
  #  post :alipay_notify, :on => :collection
  #end

  #resources :tasks, :only => [] do
  #  get :invite, :on => :collection
  #end

  #resources :accounts, :only => [:edit, :update] do
  #  get :recharge, :on => :collection 
  #  get :info, :on => :collection
  #  get :status, :on => :collection
  #end

  #resources :roles

  root :to => 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout "application_control"

  def index
    @notices = Notice.limit(10).order("pdt_date DESC")
    @cmpt_cstrs = Report.where(:category => Setting.reports.ctg_cstr_id).limit(10).order("pdt_date DESC")
    @cmpt_servs = Report.where(:category => Setting.reports.ctg_serv_id).limit(10).order("pdt_date DESC")
    @cmpt_knows = Report.where(:category => Setting.reports.ctg_know_id).limit(10).order("pdt_date DESC")

    @act_cmpts = Activity.where(:category => Setting.activities.ctg_cmpt_id).limit(10).order("pdt_date DESC")
    @act_orgs = Activity.where(:category => Setting.activities.ctg_org_id).limit(8).order("pdt_date DESC")
    @act_bases = Activity.where(:category => Setting.activities.ctg_base_id).limit(8).order("pdt_date DESC")
    @act_mebs = Activity.where(:category => Setting.activities.ctg_meb_id).limit(8).order("pdt_date DESC")

    @results = Result.all

    @carousels = Carousel.all

    @showrooms = Showroom.all
  end
end

app/helpers/home_helper.rb
module HomeHelper

  def activity_ctg 
    hash = {}
    hash[Setting.activities.ctg_cmpt_id] = Setting.activities.ctg_cmpt
    hash[Setting.activities.ctg_org_id]  = Setting.activities.ctg_org
    hash[Setting.activities.ctg_base_id] = Setting.activities.ctg_base
    hash[Setting.activities.ctg_meb_id]  = Setting.activities.ctg_meb
    hash
  end

  def report_ctg 
    hash = {}
    hash[Setting.reports.ctg_cstr_id] = Setting.reports.ctg_cstr
    hash[Setting.reports.ctg_serv_id]  = Setting.reports.ctg_serv
    hash[Setting.reports.ctg_know_id] = Setting.reports.ctg_know
    hash
  end
end

app/views/home/index.html.haml
- provide(:title, t('.title'))

-#
  .container.home-index
  .row
    .col-12
      %h2
        找比中
    .col-12
      #custom-search-input
        .input-group
          %input.search-query.form-control{:placeholder => "", :type => "text"}/
          %span.input-group-btn
            %button{:disabled => "disabled", :type => "button"}
              %span.fa.fa-search
%section.mt-4
  .container.py-2.bg-white
    .row
      -#
        .col-3
          .card.rounded-0.border-0
            -#
              .card-header.bg-white.text-primary.p-2
                业务办理地址
            .card-body.p-0
              %ul.list-group.list-group-flush
                %li.list-group-item.py-e.bg-2eacce.text-white
                  %p
                    崇文新区东门南梁山水务客服中心
                  客服热线:7360555
                %li.list-group-item.py-3.bg-2eacce.text-white
                  %p
                    新城政务中心服务大厅梁山水务业务办理窗口
                  客服热线:7366767
      .col-12
        %main{:role => "main"}
          #carouselExampleIndicators.carousel.slide{"data-ride" => "carousel"}
            %ol.carousel-indicators
              - @carousels.each_with_index do |c, i|          
                %li{:class => i == 0 ? "active" : '', "data-slide-to" => i.to_s, "data-target" => "#carouselExampleIndicators"}
            .carousel-inner.rounded-0
              - @carousels.each_with_index do |c, i|          
                .carousel-item{:class => i == 0 ? "active" : ''}
                  = image_tag c.photo, :class => "d-block w-100"
            %a.carousel-control-prev{"data-slide" => "prev", :href => "#carouselExampleIndicators", :role => "button"}
              %span.carousel-control-prev-icon{"aria-hidden" => "true"}
              %span.sr-only Previous
            %a.carousel-control-next{"data-slide" => "next", :href => "#carouselExampleIndicators", :role => "button"}
              %span.carousel-control-next-icon{"aria-hidden" => "true"}
              %span.sr-only Next
      -#
        .col-12.col-sm-3
        .row
          .col-12
            = image_tag "swhms.png", :class => "d-block w-100"
          .col-6.pl-0
            .border.text-center.pt-4.mb-2.py-2.bg-info
              = link_to result_path(@results[0]) do 
                %p.mb-0
                  %i.fa.fa-group.fa-4x.text-white
                %p.mb-0.text-white
                  我的用水
            .border.text-center.pt-4.py-2.bg-primary
              = link_to result_path(@results[1]) do 
                %p.mb-0
                  %i.fa.fa-id-badge.fa-4x.text-white
                %p.mb-0.text-white
                  水费查询
          .col-6.pl-0
            .border.d-flex.justify-content-center.align-items-center.py-3.mb-1.bg-success
              = link_to result_path(@results[2]) do 
                %p.mb-0
                  %i.fa.fa-user.text-white
                    办理指南
            .border.d-flex.justify-content-center.align-items-center.py-3.mb-1.bg-warning
              = link_to result_path(@results[3]) do 
                %p.mb-0
                  %i.fa.fa-list.text-white
                    服务网点
            .border.d-flex.justify-content-center.align-items-center.py-3.mb-1.bg-dark
              = link_to result_path(@results[4]) do 
                %p.mb-0
                  %i.fa.fa-mobile.text-white
                    用户报装
            .border.d-flex.justify-content-center.align-items-center.py-3.mb-1.bg-danger
              = link_to result_path(@results[5]) do 
                %p.mb-0
                  %i.fa.fa-map.text-white
                    网上缴费

%section.mt-3
  .container
    -#
      .row.mb-3
      .col-12
        = image_tag "syhf.jpg", :class => "w-100"
    .row
      .col-sm-6.mb-3
        .card.rounded-0
          .card-header.rounded-0.p-2.qijianbox-title
            通知公告
            %span.pull-right
              = link_to '>>', notices_path, :class => 'text-white' 
          .card-body.px-0.py-1
            %ul.mb-0.pr-3
              - @notices.each do |notice|
                %li.py-1.text-dark
                  .row
                    .col-7.col-sm-8.text-truncate
                      = link_to notice.title, notice_path(notice), :class => "text-body"
                    .col-5.col-sm-4
                      %p.text-muted.text-right.font-weight-light.mb-0
                        = notice.pdt_date.strftime('%Y-%m-%d')
      .col-sm-6.mb-3
        -#
          .row.mb-3
          .col-12
            = image_tag "wscl.jpg", :class => "w-100"
        .card.rounded-0
          .card-header.rounded-0.p-2.qijianbox-title
            = Setting.reports.ctg_cstr
            %span.pull-right
              = link_to '>>', cstr_reports_path, :class => 'text-white' 
          .card-body.px-0.py-1
            %ul.mb-0.pr-3
              - @cmpt_cstrs.each do |cstr|
                %li.py-1.text-primary
                  .row
                    .col-7.col-sm-8.text-truncate
                      = link_to cstr.title, report_path(cstr), :class => "text-body"
                    .col-5.col-sm-4
                      %p.text-muted.text-right.font-weight-light.mb-0
                        = cstr.pdt_date.strftime('%Y-%m-%d')
                    -#
                      .col-2
                        %p.text-muted.font-weight-light.mb-0
                          48.00万

      .col-sm-6.mb-3
        .card.rounded-0
          .card-header.rounded-0.p-2.qijianbox-title
            = Setting.reports.ctg_know
            %span.pull-right
              = link_to '>>', know_reports_path, :class => 'text-white' 
          .card-body.px-0.py-1
            %ul.mb-0.pr-3
              - @cmpt_knows.each do |know|
                %li.py-1.text-info
                  .row
                    .col-7.col-sm-8.text-truncate
                      = link_to know.title, report_path(know), :class => "text-body"
                    .col-5.col-sm-4
                      %p.text-muted.text-right.font-weight-light.mb-0
                        = know.pdt_date.strftime('%Y-%m-%d')

      .col-sm-6.mb-3
        .card.rounded-0
          .card-header.rounded-0.p-2.qijianbox-title
            = Setting.reports.ctg_serv
            %span.pull-right
              = link_to '>>', serv_reports_path, :class => 'text-white' 
          .card-body.px-0.py-1
            %ul.mb-0.pr-3
              - @cmpt_servs.each do |serv|
                %li.py-1.text-success
                  .row
                    .col-7.col-sm-8.text-truncate
                      = link_to serv.title, report_path(serv), :class => "text-body"
                    .col-5.col-sm-4
                      %p.text-muted.text-right.font-weight-light.mb-0
                        = serv.pdt_date.strftime('%Y-%m-%d')

%section.mb-3
  .container
    .row
      .col-12.col-sm-3.mb-3
        .card.rounded-0
          .card-header.dangjianbox-title.p-2
            公司党建
          .card-body.px-0.py-1
            %ul.mb-0
              - @act_cmpts.each do |cmpt|
                %li.py-1.text-danger
                  = link_to truncate(cmpt.title, :length => 14), activity_path(cmpt), :class => "text-body"
      .col-12.col-sm-9
        .row.mb-3
          .col-12
            = image_tag "dangjian.png", :class => "w-100"
        .card.rounded-0
          .card-header.dangjianbox-title.p-2
            党建工作
          .card-body.px-0.py-1
            %ul.mb-0.pr-3
              - @act_orgs.each do |org|
                %li.py-1.text-danger
                  .row
                    .col-7.col-sm-8.text-truncate
                      = link_to org.title, activity_path(org), :class => "text-body"
                    .col-5.col-sm-4
                      %p.text-muted.text-right.font-weight-light.mb-0
                        = org.pdt_date.strftime('%Y-%m-%d')
                -#
                  %a#nav-law-tab.nav-item.nav-link{"aria-controls" => "nav-law", "aria-selected" => "false", "data-toggle" => "tab", :href => "#nav-law", :role => "tab"} 
                    基层党组织建设
                  %a#nav-score-tab.nav-item.nav-link{"aria-controls" => "nav-score", "aria-selected" => "false", "data-toggle" => "tab", :href => "#nav-score", :role => "tab"}
                    党员队伍建设
            -#
              #nav-law.tab-pane.fade{"aria-labelledby" => "nav-law-tab", :role => "tabpanel"}
              %ul.mb-0
                - @act_bases.each do |base|
                  %li.py-1.text-primary
                    .row
                      .col-10
                        = link_to truncate(base.title, :length => 35), activity_path(base), :class => "text-body"
                      .col-2
                        %p.text-muted.font-weight-light.mb-0
                          = base.created_at.strftime('%Y-%m-%d')
            -#
              #nav-score.tab-pane.fade{"aria-labelledby" => "nav-score-tab", :role => "tabpanel"}
              %ul.mb-0
                - @act_mebs.each do |meb|
                  %li.py-1.text-primary
                    .row
                      .col-10
                        = link_to truncate(meb.title, :length => 35), activity_path(meb), :class => "text-body"
                      .col-2
                        %p.text-muted.font-weight-light.mb-0
                          = meb.created_at.strftime('%Y-%m-%d')

%section.my-3
  .container
    .row
      .col-12.col-sm-3
        .card.rounded-0.mb-3
          .card-header.p-2.rounded-0.qiyezhanting-title
            企业展厅
          .card-body.p-2
            - if !@showrooms.blank?
              .row
                - @showrooms[0..1].each do |room|
                  -#
                    .image-grid-cover{:style => "background-image: url(#{image_url(room.photo)});"}
                  .col-12.mb-2
                    = image_tag room.photo
            -#
              .border.d-flex.justify-content-center.align-items-center.mb-1
                %a{:href => "#"}
                  = image_tag "xwyd.gif"
              .border.d-flex.justify-content-center.align-items-center.mb-1
                %a{:href => "#"}
                  = image_tag "xwyd.gif"
        .card.rounded-0
          .card-header.youqing-title.rounded-0.p-2
            友情链接
          .card-body.p-2
            .row
              .col-12
                = link_to "济宁市人民政府", "http://www.jining.gov.cn/", :class => "text-muted", :target => "_blank"
              .col-12
                = link_to "济宁市城乡水务局", "http://jnsl.jining.gov.cn/", :class => "text-muted", :target => "_blank"
              .col-12
                = link_to "山东公用控股有限公司", "http://www.sdgykg.com/", :class => "text-muted", :target => "_blank"
              -#
                .col-7
                  = link_to "四川省发改委", "#", :class => "text-muted"
                .col-5
                  = link_to "四川日报", "#", :class => "text-muted"
                
      .col-12.col-sm-9
        .row.mb-3
          .col-12
            = image_tag "shuiwu.jpg", :class => "w-100"
        .row
          - if !@showrooms.blank?
            - @showrooms[2..-1].each do |room|
              .col-4.mb-3
                = image_tag room.photo
                -#
                  .image-grid-cover{:style => "background-image: url(#{image_url(room.photo)});"}

          -#
            #cptMembIndicators.carousel.slide{"data-ride" => "carousel"}
              %ol.carousel-indicators
                %li.active{"data-slide-to" => "0", "data-target" => "#cptMembIndicators"}
                %li{"data-slide-to" => "1", "data-target" => "#cptMembIndicators"}
                %li{"data-slide-to" => "2", "data-target" => "#cptMembIndicators"}
              .carousel-inner.rounded-0
                .carousel-item.active
                  = image_tag "car1.png", :class => "d-block w-100"
                  .carousel-caption.d-none.d-md-block
                    %h5
                    %p
                .carousel-item
                  = image_tag "car1.png", :class => "d-block w-100"
                .carousel-item
                  = image_tag "car1.png", :class => "d-block w-100"
              %a.carousel-control-prev{"data-slide" => "prev", :href => "#cptMembIndicators", :role => "button"}
                %span.carousel-control-prev-icon{"aria-hidden" => "true"}
                %span.sr-only Previous
              %a.carousel-control-next{"data-slide" => "next", :href => "#cptMembIndicators", :role => "button"}
                %span.carousel-control-next-icon{"aria-hidden" => "true"}
                %span.sr-only Next
            

app/views/home/index2.html.haml
- provide(:title, t('.title'))

%main{:role => "main"}
  %section.text-center
    .container.px-0
      .card.bg-dark.text-white.border-0
        = image_tag "home-main.jpg", :class => "card-img"
        .card-img-overlay
          %h5.card-title Card title
          %p.card-text.text-center 新能源
          %p.card-text Last updated 3 mins ago
  .album.py-3
    .container.px-0
      .row
        .col-md-9
          .row
            .col-md-4
              .card.mb-4.box-shadow
                = image_tag "one.jpg", :class => "card-img-top"
                .card-body
                  %p.card-text.text-center 新能源
            .col-md-4
              .card.mb-4.box-shadow
                = image_tag "one.jpg", :class => "card-img-top"
                .card-body
                  %p.card-text.text-center 新能源
            .col-md-4
              .card.mb-4.box-shadow
                = image_tag "one.jpg", :class => "card-img-top"
                .card-body
                  %p.card-text.text-center 新能源
            .col-md-4
              .card.mb-4.box-shadow
                = image_tag "one.jpg", :class => "card-img-top"
                .card-body
                  %p.card-text.text-center 新能源
            .col-md-4
              .card.mb-4.box-shadow
                = image_tag "one.jpg", :class => "card-img-top"
                .card-body
                  %p.card-text.text-center 新能源
            .col-md-4
              .card.mb-4.box-shadow
                = image_tag "one.jpg", :class => "card-img-top"
                .card-body
                  %p.card-text.text-center 新能源
        .col-md-3
          .card
            .card-header.bg-primary.text-light
              了解更多
            .card-body.p-0
              %ul.list-group.list-group-flush
                - @notices.each do |notice|
                  = link_to truncate(notice.title, :length => 14), notice_path(notice), :class => "list-group-item list-group-item-action border-0"
              -#
                %marquee{ :behavior => "scroll", :bgcolor => "#ffffff", :direction => "up", :hspace => "0", :onmouseout => "this.start()", :onmouseover => "this.stop()", :scrollamount => "1", :scrolldelay => "10", :vspace => "10"}