config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  #devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  #devise_scope :user do
  #  get 'forget', to: 'users/passwords#forget'
  #  patch 'update_password', to: 'users/passwords#update_password'
  #end

  #require 'sidekiq/web'
  #require 'sidekiq/cron/web'
  #mount Sidekiq::Web => '/sidekiq'


  resources :labs, :only => [:index, :show]
  resources :members, :only => [:index, :show]
  resources :results, :only => [:index, :show]
  resources :reports, :only => [:index, :show] do
    get :cstr, :on => :collection
    get :serv, :on => :collection
    get :know, :on => :collection
  end
  resources :activities, :only => [:index, :show]
  resources :manages, :only => [:index, :show]
  resources :notices, :only => [:index, :show]
  resources :infos, :only => [:index, :show]

  #resources :controls, :only => [:index]

  #resources :systems, :only => [] do
  #  get :send_confirm_code, :on => :collection
  #end

  #resources :users, :only => []  do
  #  get :center, :on => :collection
  #  get :alipay_return, :on => :collection
  #  post :alipay_notify, :on => :collection
  #  get :mobile_authc_new, :on => :member
  #  post :mobile_authc_create, :on => :member
  #  get :mobile_authc_status, :on => :member

  #end

  #resources :orders, :only => [:new, :create] do
  #  get :pay, :on => :collection
  #  get :alipay_return, :on => :collection
  #  post :alipay_notify, :on => :collection
  #end

  #resources :tasks, :only => [] do
  #  get :invite, :on => :collection
  #end

  #resources :accounts, :only => [:edit, :update] do
  #  get :recharge, :on => :collection 
  #  get :info, :on => :collection
  #  get :status, :on => :collection
  #end

  #resources :roles

  root :to => 'home#index'
end

app/models/report.rb
class Report < ActiveRecord::Base

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  layout "application_control"

  def index
    @reports = Report.all.order("pdt_date DESC").page( params[:page]).per( Setting.systems.per_page ) 
  end

  def show
    @report = Report.find(params[:id])
  end

  def cstr 
    @reports = Report.where(:category => Setting.reports.ctg_cstr_id).order("pdt_date DESC").page( params[:page]).per( Setting.systems.per_page ) 
  end
  
  def serv 
    @reports = Report.where(:category => Setting.reports.ctg_serv_id).order("pdt_date DESC").page( params[:page]).per( Setting.systems.per_page ) 
  end

  def know 
    @reports = Report.where(:category => Setting.reports.ctg_know_id).order("pdt_date DESC").page( params[:page]).per( Setting.systems.per_page ) 
  end
end

app/views/reports/cstr.html.haml
- provide(:title, t('.title'))

- content_for :sidebar_body do
  -#
    = link_to Setting.reports.tag, reports_path, :class => "list-group-item text-dark"
  = link_to Setting.reports.ctg_cstr, cstr_reports_path, :class => "list-group-item text-dark"
  = link_to Setting.reports.ctg_serv, serv_reports_path, :class => "list-group-item text-dark"
  = link_to Setting.reports.ctg_know, know_reports_path, :class => "list-group-item text-dark"
  -#
    = link_to Setting.activities.tag, activities_path, :class => "list-group-item text-dark"

- content_for :content_body do
  %ul.list-group.list-group-flush
    - @reports.each_with_index do |report, index|
      = link_to report_path(report), :class => "list-group-item list-group-item-action" do
        .row
          .col-7.col-sm-10.text-truncate
            %p.mb-0.text-truncate
              = '[' + report_ctg[report.category] + ']'
              = report.title
          .col-5.col-sm-2.text-right
            %p.text-muted.font-weight-light.mb-0
              - if report.pdt_date 
                = report.pdt_date.strftime('%Y-%m-%d')
              - else
                = report.created_at.strftime('%Y-%m-%d')
  .row.mt-3
    .col-md-12.site-theme-paginate-wrapper.d-flex.justify-content-center
      = paginate @reports, window: 2, left: 1, right: 1 

= render "layouts/control_panel"

app/views/reports/index.html.haml
- provide(:title, t('.title'))

- content_for :sidebar_body do
  = link_to Setting.reports.tag, reports_path, :class => "list-group-item text-dark"
  -#
    = link_to Setting.activities.tag, activities_path, :class => "list-group-item text-dark"

- content_for :content_body do
  %ul.list-group.list-group-flush
    - @reports.each_with_index do |report, index|
      = link_to report_path(report), :class => "list-group-item list-group-item-action" do
        .row
          .col-7.col-sm-10.text-truncate
            %p.mb-0.text-truncate
              = '[' + report_ctg[report.category] + ']'
              = report.title
          .col-5.col-sm-2.text-right
            %p.text-muted.font-weight-light.mb-0
              - if report.pdt_date 
                = report.pdt_date.strftime('%Y-%m-%d')
              - else
                = report.created_at.strftime('%Y-%m-%d')
  .row.mt-3
    .col-md-12.site-theme-paginate-wrapper.d-flex.justify-content-center
      = paginate @reports, window: 2, left: 1, right: 1 

= render "layouts/control_panel"

app/views/reports/know.html.haml
- provide(:title, t('.title'))

- content_for :sidebar_body do
  -#
    = link_to Setting.reports.tag, reports_path, :class => "list-group-item text-dark"
  = link_to Setting.reports.ctg_cstr, cstr_reports_path, :class => "list-group-item text-dark"
  = link_to Setting.reports.ctg_serv, serv_reports_path, :class => "list-group-item text-dark"
  = link_to Setting.reports.ctg_know, know_reports_path, :class => "list-group-item text-dark"
  -#
    = link_to Setting.activities.tag, activities_path, :class => "list-group-item text-dark"

- content_for :content_body do
  %ul.list-group.list-group-flush
    - @reports.each_with_index do |report, index|
      = link_to report_path(report), :class => "list-group-item list-group-item-action" do
        .row
          .col-7.col-sm-10.text-truncate
            %p.mb-0.text-truncate
              = '[' + report_ctg[report.category] + ']'
              = report.title
          .col-5.col-sm-2.text-right
            %p.text-muted.font-weight-light.mb-0
              - if report.pdt_date 
                = report.pdt_date.strftime('%Y-%m-%d')
              - else
                = report.created_at.strftime('%Y-%m-%d')
  .row.mt-3
    .col-md-12.site-theme-paginate-wrapper.d-flex.justify-content-center
      = paginate @reports, window: 2, left: 1, right: 1 

= render "layouts/control_panel"

app/views/reports/serv.html.haml
- provide(:title, t('.title'))

- content_for :sidebar_body do
  -#
    = link_to Setting.reports.tag, reports_path, :class => "list-group-item text-dark"
  = link_to Setting.reports.ctg_cstr, cstr_reports_path, :class => "list-group-item text-dark"
  = link_to Setting.reports.ctg_serv, serv_reports_path, :class => "list-group-item text-dark"
  = link_to Setting.reports.ctg_know, know_reports_path, :class => "list-group-item text-dark"
  -#
    = link_to Setting.activities.tag, activities_path, :class => "list-group-item text-dark"

- content_for :content_body do
  %ul.list-group.list-group-flush
    - @reports.each_with_index do |report, index|
      = link_to report_path(report), :class => "list-group-item list-group-item-action" do
        .row
          .col-7.col-sm-10.text-truncate
            %p.mb-0.text-truncate
              = '[' + report_ctg[report.category] + ']'
              = report.title
          .col-5.col-sm-2.text-right
            %p.text-muted.font-weight-light.mb-0
              - if report.pdt_date 
                = report.pdt_date.strftime('%Y-%m-%d')
              - else
                = report.created_at.strftime('%Y-%m-%d')
  .row.mt-3
    .col-md-12.site-theme-paginate-wrapper.d-flex.justify-content-center
      = paginate @reports, window: 2, left: 1, right: 1 

= render "layouts/control_panel"

app/views/reports/show.html.haml
- provide(:title, t('.title'))

- content_for :sidebar_body do
  = link_to Setting.reports.tag, reports_path, :class => "list-group-item text-dark"
  -#
    = link_to Setting.activities.tag, activities_path, :class => "list-group-item text-dark"

- content_for :content_body do
  %h5.text-center.mt-3
    = @report.title
  %p.text-center
    -#
      %small
        = '分类：' + report_ctg[@report.category]
    %small
      - if @report.pdt_date 
        = "发布时间: " +  @report.pdt_date.strftime('%Y-%m-%d')
      - else
        = "发布时间: " +  @report.created_at.strftime('%Y-%m-%d')
  %hr
  = @report.content.nil? ? '' : @report.content.html_safe

= render "layouts/control_panel"